package rulesystem.analyzer;
import rulesystem.ast.*;
import java.util.*;

public class ConflictDetector {

    /**
     * Detecta conflictos: múltiples reglas con la misma acción.
     * Excluye grupos que ya son redundancias (misma condición Y misma acción),
     * porque el enunciado los trata como categorías separadas.
     */
    public void detect(Program program) {
        // Primero identificar firmas redundantes para excluirlas
        Set<String> redundantSignatures = new HashSet<>();
        Map<String, Integer> sigCount = new HashMap<>();
        for (Rule rule : program.getRules()) {
            String sig = rule.getSignature();
            sigCount.put(sig, sigCount.getOrDefault(sig, 0) + 1);
        }
        for (Map.Entry<String, Integer> e : sigCount.entrySet()) {
            if (e.getValue() > 1) redundantSignatures.add(e.getKey());
        }

        // Agrupar por acción solo las reglas que NO son todas redundantes entre sí
        Map<String, List<String>> actionMap = new LinkedHashMap<>();
        for (Rule rule : program.getRules()) {
            // Si esta regla es parte de un grupo redundante, no la contamos como conflicto
            if (redundantSignatures.contains(rule.getSignature())) continue;
            String action = rule.getAction().getFactName();
            actionMap.computeIfAbsent(action, k -> new ArrayList<>()).add(rule.getName());
        }

        for (Map.Entry<String, List<String>> entry : actionMap.entrySet()) {
            if (entry.getValue().size() > 1) {
                System.out.println("Action " + entry.getKey() +
                    " generated by " + String.join(", ", entry.getValue()));
            }
        }
    }
}