package rulesystem.analyzer;

import rulesystem.ast.*;

import java.util.*;

public class ConflictDetector {

    public void detect(Program program) {
        Map<String, List<String>> actionMap = new HashMap<>();

        for (Rule rule : program.getRules()) {
            String action = rule.getAction().getFactName();

            actionMap
                .computeIfAbsent(action, k -> new ArrayList<>())
                .add(rule.getName());
        }

        for (Map.Entry<String, List<String>> entry : actionMap.entrySet()) {
            if (entry.getValue().size() > 1) {
                System.out.println(
                    "Action " + entry.getKey() +
                    " generated by " + String.join(", ", entry.getValue())
                );
            }
        }
    }
}